version: '3'
services:
  gcloud:
    build: .
    environment:
      TF_VAR_project: ${TF_VAR_project}
    volumes:
      - .:/app
    networks:
      - gcloud-test

networks:
  gcloud-test:
    driver: "bridge"
